# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "Debian73_Wheezy64"
    webserver.vm.network :forwarded_port, guest: 80, host: 8080
    webserver.vm.network :private_network, ip: "192.168.33.10"
  end

  config.vm.define "webapp" do |webapp|
    webapp.vm.box = "Debian73_Wheezy64"
    webapp.vm.network :private_network, ip: "192.168.33.11"
  end

  config.vm.define "db" do |db|
    db.vm.box = "Debian73_Wheezy64"
    db.vm.network :private_network, ip: "192.168.33.12"
  end

  config.vm.define "salt_master" do |salt_master|
    salt_master.vm.box = "Debian73_Wheezy64"
    salt_master.vm.network :private_network, ip: "192.168.33.13"
    salt_master.vm.synced_folder "~/workspace/monsterlab/viper/", "/viper_data/"
  end

end
